name: Render to PDF

on:
  push:
    branches: ['master']

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish PDF Document
        id: document
        uses: shrink/actions-document-publish@v1
        with:
          sources: 'docs/README.md'

      - name: Upload Document
        uses: actions/upload-artifact@v2
        with:
          name: 'document.pdf'
          path: ${{ steps.document.outputs.pdf }}